### PR TITLE
cmd/bsky-webhook: add support for facets

### LINKED ISSUE #9: Links are being truncated
When someone sends a link, the content that we get only shows the truncated form of the link and clicking it in Slack visits the wrong URL.

Ideally we parse the facet for the link and convert it to Slack markdown or place the full URL.

example: https://bsky.app/profile/pablomxnl.bsky.social/post/3lbzijeus4c2i
image
image

### PR DESCRIPTION
**Pull request by Erisa**
Reference: https://docs.bsky.app/docs/advanced-guides/post-richtext
Fixes #9

Tested working with links, mentions, and tags. Seeking a quick review to ensure I didn't commit any Go crimes in the process.

### CODE REVIEW

File: cmd/bsky-webhook/facets.go [hunk 1]
```diff
@@ -0,0 +1,90 @@
+package main
+
+import (
+	"fmt"
+	"slices"
+	"strings"
+)
+
+func bskyMessageToSlackMarkup(bskyMessage BskyMessage) (string, error) {
```
Comment (creachadair) [inline cmd/bsky-webhook/facets.go]: An optional general suggestion:

For parameters in small scopes where their meaning is close to its use, it's fine (and indeed conventionally preferable) to choose less verbose names. Since the type is right here, this could be `message` or even simply `msg`, there is only one message involved here.

In particular, I recommend against re-stating the type of a declared variable in the name, unless for some reason it makes a distinction (e.g., "fooString" vs. "fooBytes" if we had both formats to deal with)

File: cmd/bsky-webhook/facets.go [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+}
+
+func facetsToFragments(bskyMessage BskyMessage) ([]BskyTextFragment, error) {
+	facets := bskyMessage.Commit.Record.Facets
+	textString := bskyMessage.Commit.Record.Text
+
+	fragments := []BskyTextFragment{}
+
+	slices.SortStableFunc(facets, func(a, b BskyFacet) int {
+		return a.Index.ByteStart - b.Index.ByteStart
```
Comment (creachadair) [inline cmd/bsky-webhook/facets.go]:
```go
return cmp.Compare(a.Index.ByteStart, b.Index.ByteStart)
```

File: cmd/bsky-webhook/types.go [hunk 3]
```diff
@@ -50,6 +51,28 @@ type BskyImageRef struct {
...
 }
 
+type BskyFacet struct {
+	Features []BskyFacetFeatures `json:"features"`
+	Index    BskyFacetIndex      `json:"index"`
+}
+
+type BskyFacetFeatures struct {
+	Type string `json:"$type"`
+	Uri  string `json:"uri"`
```
Comment (creachadair) [inline cmd/bsky-webhook/types.go]: [By convention](https://go.dev/wiki/CodeReviewComments#initialisms) these should be `URI` and `DID`.

File: cmd/bsky-webhook/types.go [hunk 4]
```diff
@@ -50,6 +51,28 @@ type BskyImageRef struct {
...
+	Did  string `json:"did"`
```
Comment (creachadair) [inline cmd/bsky-webhook/types.go]: Do we need the names explicitly here? It appears we only use these for decoding, and the JSON decoder does a case-insensitive match anyway. (We do need `$type` because of the spelling difference, but I mean the others)

File: cmd/bsky-webhook/types.go [hunk 5]
```diff
@@ -29,9 +29,10 @@ type BskyCommit struct {
 }
 
 type BskyRecord struct {
-	Text            string    `json:"text"`
-	Embed           BskyEmbed `json:"embed"`
-	CreatedAtString string    `json:"createdAt"`
+	Text            string      `json:"text"`
+	Embed           BskyEmbed   `json:"embed"`
+	CreatedAtString string      `json:"createdAt"`
```
Comment (creachadair) [inline cmd/bsky-webhook/types.go]: Maybe a comment noting the expected format? (Is this RFC3339 or something?)

File: cmd/bsky-webhook/main.go [hunk 6]
```diff
@@ -288,12 +288,24 @@ func getBskyProfile(ctx context.Context, bskyMessage BskyMessage, bsky *bluesky.
...
+	var messageText string
+	var err error
+
+	if len(bskyMessage.Commit.Record.Facets) != 0 {
+		messageText, err = bskyMessageToSlackMarkup(bskyMessage)
+		if err != nil {
+			return err
+		}
+	} else {
+		messageText = bskyMessage.Commit.Record.Text
```
Comment (creachadair) [inline cmd/bsky-webhook/main.go]: Could maybe have `bskyMessageToSlackMarkup` handle this case so you don't have to check for it here? (Actually I think it might already)

File: cmd/bsky-webhook/facets.go [hunk 7]
```diff
@@ -0,0 +1,90 @@
...
+				} else if feature.Type == "app.bsky.richtext.facet#tag" {
+					uri = fmt.Sprintf("https://bsky.app/hashtag/%s", feature.Tag)
+				}
+			}
+			if uri != "" {
+				slackStringBuilder.WriteString(fmt.Sprintf("<%s|%s>", uri, fragment.Text))
+			} else {
+				slackStringBuilder.WriteString(fragment.Text)
+			}
+		}
```
Comment (creachadair) [inline cmd/bsky-webhook/facets.go]: I think this loop could be simplified quite a bit with a helper method:

```go
func (b BskyFacet) featureURI() string {
   for _, feat := range b.Features {
      switch feat.URI {
      case "app.bsky.richtext.facet#link":
         return feat.URI
      case "app.bsky.richtext.facet#mention":
         return fmt.Sprintf("https://bsky.app/profile/%s", feat.DID)
      case "app.bsky.richtext.facet#tag":
         return fmt.Sprintf("https://bsky.app/hashtag/%s", feat.Tag)
      }
   }
   return ""
}
```

Then the whole body of the (outer) loop can be something like:

```go
for _, frag := range fragments {
   if uri := frag.featureURI(); uri != "" {
      fmt.Fprintf(&sb, "<%s|%s>", uri, frag.Text)
   } else {
      sb.WriteString(frag.Text)
   }
}
```

(Note as illustrated here, you can use the builder as an `io.Writer` and format directly into it)

File: cmd/bsky-webhook/facets.go [hunk 8]
```diff
@@ -0,0 +1,90 @@
+package main
+
+import (
+	"fmt"
+	"slices"
+	"strings"
+)
+
+func bskyMessageToSlackMarkup(bskyMessage BskyMessage) (string, error) {
+	var slackStringBuilder strings.Builder
```
Comment (creachadair) [inline cmd/bsky-webhook/facets.go]: I don't think this needs to say so much, there's only one string builder here:
```go
var sb strings.Builder
```

File: cmd/bsky-webhook/facets.go [hunk 9]
```diff
@@ -0,0 +1,90 @@
...
+	facets := bskyMessage.Commit.Record.Facets
+	textString := bskyMessage.Commit.Record.Text
+
+	fragments := []BskyTextFragment{}
+
+	slices.SortStableFunc(facets, func(a, b BskyFacet) int {
+		return a.Index.ByteStart - b.Index.ByteStart
+	})
+
+	textCursor := 0
```
Comment (creachadair) [inline cmd/bsky-webhook/facets.go:53]: If I understand correctly, the delicate dance with indices here is something to do with the fact that facets are specified by offsets into the base text?

Given that you went to the trouble of ordering them above, maybe this could be turned into a helper that uses `slices.BinarySearch` (or even just scans them linearly—there aren't going to be that many, we don't need to worry about asymptotics I think) to find the relevant fragment for each facet? (Even if we do care, we already spent O(n lg n) to sort them, so spending another n lg n to probe them won't affect the underlying shape)

I am _sort of_ convinced this does what I described above, but index dancing is hard to follow, so I would suggest we try to be more obvious here. 

(Then too, I think maybe we don't need to do any additional appending, since the facet decorations could be glued directly into place on the ~facet~ fragment they belong to I think?)

File: cmd/bsky-webhook/facets.go (hunk 2 above)
Comment (creachadair) [reply cmd/bsky-webhook/facets.go]: Though if you really care about stability, maybe what we want here is a tie breaker, e.g.,

```go
if c := cmp.Compare(a.Index.ByteStart, b.Index.ByteStart); c != 0 {
   return c
}
return cmp.Compare(b.Index.ByteEnd, a.Index.ByteEnd)
```

or something like that (so they have proper nesting order within the ties) 

YMMV.

File: cmd/bsky-webhook/types.go (hunk 4 above)
Comment (Erisa) [reply cmd/bsky-webhook/types.go]: I think (personally) that being explicit is best because it doesn't result in confusion in naming or capitalisation later down the line if we do encode back again, especially since some other types `SlackAttachment` and `SlackBody` are used for encoding.

I'm willing to move on that if a Go convention says that they shouldn't be explicit, though!

File: cmd/bsky-webhook/types.go (hunk 5 above)
Comment (Erisa) [reply cmd/bsky-webhook/types.go]: I can't easily find a spec that says what it should be, but we parse it as RFC3339 so I can add that.

File: .env
Comment (creachadair) [inline .env:1]: I expect we probably don't want to commit this file to the repo. Maybe add it to .gitignore?

**Review by creachadair — APPROVED** [review]

File: .env
Comment (Erisa) [reply .env:1]: Oops. Luckily just test credentials, removed and added a gitignore
